/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg002.b.wmaldonado8;

/**
 *
 * @author PCD
 */
public class Diseño extends javax.swing.JFrame {

    /**
     * Creates new form Diseño
     */
    public Diseño() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        registroCA = new javax.swing.JMenuItem();
        registroCP = new javax.swing.JMenuItem();
        registroCH = new javax.swing.JMenuItem();
        depositarR = new javax.swing.JMenuItem();
        depositarC_hipotecaria = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("                                              MENU PRINCIPAL");

        jMenu1.setText("Ingresar");

        registroCA.setText("Registrar Cuenta Ahorro");
        registroCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroCAActionPerformed(evt);
            }
        });
        jMenu1.add(registroCA);

        registroCP.setText("Registrar Cuenta Prestamo");
        registroCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroCPActionPerformed(evt);
            }
        });
        jMenu1.add(registroCP);

        registroCH.setText("Registrar Cuenta Hipoteca");
        registroCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroCHActionPerformed(evt);
            }
        });
        jMenu1.add(registroCH);

        depositarR.setText("Depositar o Retirar");
        depositarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarRActionPerformed(evt);
            }
        });
        jMenu1.add(depositarR);

        depositarC_hipotecaria.setText("Depositar Cuenta Hipotecaria");
        jMenu1.add(depositarC_hipotecaria);

        salir.setText("Guardar");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuItem1.setText("Presentar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroCHActionPerformed
        // TODO add your handling code here:
        cuenta_Hipoteca ch = new cuenta_Hipoteca();
        ch.setVisible(true);
    }//GEN-LAST:event_registroCHActionPerformed

    private void depositarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarRActionPerformed
        // TODO add your handling code here:
        Depositos_Retiros dr= new Depositos_Retiros();
        dr.setVisible(true);
    }//GEN-LAST:event_depositarRActionPerformed

    private void registroCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroCAActionPerformed
        // TODO add your handling code here:
        cuenta_Ahorro ca= new cuenta_Ahorro();
        ca.setVisible(true);
    }//GEN-LAST:event_registroCAActionPerformed

    private void registroCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroCPActionPerformed
        // TODO add your handling code here:
        cuenta_Prestamo cp = new cuenta_Prestamo();
        cp.setVisible(true);
    }//GEN-LAST:event_registroCPActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_salirMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Banco.presentar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
           // TODO add your handling code here:
           Banco.grabar();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem depositarC_hipotecaria;
    private javax.swing.JMenuItem depositarR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem registroCA;
    private javax.swing.JMenuItem registroCH;
    private javax.swing.JMenuItem registroCP;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
